#version 300 es
precision highp float;
// Quad vertices
layout(location =  0) in vec2 a_pos;
layout(location =  1) in vec2 a_uv;

// Per-instance sprite data
layout(location =  2) in vec2 i_offset;     // (ox, oy) offset position in world space
layout(location =  3) in vec2 i_scale;      // uv thing
layout(location =  4) in vec2 i_tileRepeat; // (x, y) number of tiles to repeat to fill screen
layout(location =  5) in vec4 i_tileMask;   // (tilemask, inv_tilemask), boolean vector, if sprite is tiling set to true on tilemask and false on inv_tilemask

layout(location =  6) in vec3 i_movement;   
layout(location =  7) in vec4 i_parallax;   // (x, y, x_offset, y_offset)
layout(location =  8) in vec4 i_bob;        
layout(location =  9) in vec4 i_animation1; // (frame_count, fps, frame_width_px, frame_height_px)
layout(location = 10) in vec4 i_animation2; // (start_layer, pz, start_x, start_y)
layout(location = 11) in vec2 i_animation3; // 

uniform vec2 u_resolution;
uniform vec2 u_player_pos;
uniform float u_zoomScale;
uniform float u_time;

// Autogenerated by js
const vec2 backgroundSize = vec2(0.0, 0.0);
const vec2 atlasSize = vec2(0.0, 0.0);

out vec2 v_uv;
out vec2 v_tiledOffset; 
flat out vec2 v_tileRepeat;
flat out int v_texLayer;
flat out vec4 v_textureUV;

void main() {
    // All your normal calculations
    int frameCount   = int(i_animation1.x);
    int startLayer   = int(i_animation2.x);
    vec2 frameSize     = i_animation1.zw;
    int currentFrame = int(u_time * i_animation1.y) % frameCount;
    ivec2 start        = ivec2(i_animation2.zw);
    float pz = i_animation2.y;

    vec2 scale = u_resolution / backgroundSize;
    float maxScale = max(scale.x, scale.y);
    vec2 finalScale = (backgroundSize * maxScale / u_resolution) * ((u_zoomScale * pz) * 2.0 + 1.0);

    vec2 scaledPos = a_pos * i_scale * i_tileRepeat;
    float bob = sin(u_time * 6.28318 * i_bob.z + i_bob.w);
    float t = i_movement.z == 0.0 ? 0.0 : floor(u_time / i_movement.z);
    vec2 offsetPos = i_offset + 
                    ((u_player_pos + i_parallax.zw) * i_parallax.xy) + 
                    (i_bob.xy * bob) + 
                    (i_movement.xy * t);

    vec2 worldPos = (scaledPos + (offsetPos * i_tileMask.zw)) * finalScale;
    v_tiledOffset = offsetPos * i_tileMask.xy / frameSize;
    v_uv = a_uv;
    v_tileRepeat = i_tileRepeat;

    vec2 texturePos = vec2(start.x, start.y);
    int layer = startLayer;
    if (currentFrame != 0) {
        int startWidth = (int(atlasSize.x) - start.x) / int(frameSize.x);
        int startCols = (int(atlasSize.y) - start.y) / int(frameSize.y);
        int startLayerFrames = startCols * startWidth;
        // If we are on the main layer, calculate startX and startY from 0, 0
        if (currentFrame < startLayerFrames) {
            int x = currentFrame % startWidth;
            int y = currentFrame / startWidth;
            texturePos = vec2(float(start.x) + float(x) * frameSize.x, float(start.y) + float(y) * frameSize.y);
        }
        // Overflow sprites have different calculations, where startX and startY is always (0, 0)
        else {
            int overflowWidth = int(atlasSize.x) / int(frameSize.x);
            int overflowHeight = int(atlasSize.y) / int(frameSize.y);
            int framesPerLayer = overflowWidth * overflowHeight;
            int overflowFrame = currentFrame - startLayerFrames;
            int frameInLayer = overflowFrame % framesPerLayer;
            layer = startLayer + ((overflowFrame - frameInLayer) / framesPerLayer) + 1;
            int x = frameInLayer % overflowWidth;
            int y = frameInLayer / overflowWidth;
            texturePos = vec2(float(x) * frameSize.x, float(y) * frameSize.y);
        }
    }


    v_textureUV = vec4(
        texturePos.x / atlasSize.x, 
        texturePos.y / atlasSize.y, 
        (texturePos.x + frameSize.x) / atlasSize.x, 
        (texturePos.y + frameSize.y) / atlasSize.y
    );
    v_texLayer = layer;
    gl_Position = vec4(worldPos, 0.0, 1.0);
}