#version 300 es
// Quad vertices
layout(location =  0) in vec2 a_pos;
layout(location =  1) in vec2 a_uv;

// Per-instance sprite data
layout(location =  2) in vec2 i_offset;     // (ox, oy) offset position in world space
layout(location =  3) in vec2 i_scale;      // uv thing
layout(location =  4) in vec2 i_tileRepeat; // (x, y) number of tiles to repeat to fill screen
layout(location =  5) in vec4 i_tileMask;   // (tilemask, inv_tilemask), boolean vector, if sprite is tiling set to true on tilemask and false on inv_tilemask

layout(location =  6) in vec3 i_movement;   
layout(location =  7) in vec2 i_parallax;   
layout(location =  8) in vec4 i_bob;        
layout(location =  9) in vec4 i_animation1; // (frame_count, fps, frame_width_px, frame_height_px)
layout(location = 10) in vec4 i_animation2; // (start_layer, null, start_x, start_y)
layout(location = 11) in vec2 i_animation3; // 

uniform vec2 u_resolution;
uniform vec2 u_player_pos;
uniform float u_zoomScale;
uniform float u_time;

// Autogenerated by js
const vec2 backgroundSize = vec2(0.0, 0.0);
const vec2 atlasSize = vec2(0.0, 0.0);

out vec2 v_uv;
out vec2 v_tiledOffset; 
flat out vec2 v_tileRepeat;
flat out float v_texLayer;
flat out vec4 v_textureUV;

void main() {
    // All your normal calculations
    float frameCount   = i_animation1.x;
    float startLayer   = i_animation2.x;
    vec2 frameSize     = i_animation1.zw;
    float currentFrame = mod(floor(u_time * i_animation1.y), frameCount);
    vec2 start         = i_animation2.zw;

    vec2 scale = u_resolution / backgroundSize;
    float maxScale = max(scale.x, scale.y);
    vec2 finalScale = (backgroundSize * maxScale / u_resolution) * u_zoomScale;

    vec2 scaledPos = a_pos * i_scale * i_tileRepeat;
    float bob = sin(u_time * 6.28318 * i_bob.z + i_bob.w);
    float t = i_movement.z == 0.0 ? 0.0 : floor(u_time / i_movement.z);
    vec2 offsetPos = i_offset + (u_player_pos * i_parallax) + (i_bob.xy * bob) + (i_movement.xy * t);

    vec2 worldPos = (scaledPos + (offsetPos * i_tileMask.zw)) * finalScale;
    v_tiledOffset = offsetPos * i_tileMask.xy / frameSize;
    v_uv = a_uv;
    v_tileRepeat = i_tileRepeat;

    vec2 texturePos = vec2(start.x, start.y);
    float layer = startLayer;
    if (currentFrame != 0.0) {
        float startWidth = floor((atlasSize.x - start.x) / frameSize.x);
        float startCols = floor((atlasSize.y - start.y) / frameSize.y);
        float startLayerFrames = startCols * startWidth;
        // If we are on the main layer, calculate startX and startY from 0, 0
        if (currentFrame < startLayerFrames) {
            float x = mod(currentFrame, startWidth);
            float y = floor(currentFrame / startWidth);
            texturePos = vec2(start.x + x * frameSize.x,start.y + y * frameSize.y);
        }
        // Overflow sprites have different calculations, where startX and startY is always (0, 0)
        else {
            float overflowWidth = floor(atlasSize.x / frameSize.x);
            float overflowHeight = floor(atlasSize.y / frameSize.y);
            float framesPerLayer = overflowWidth * overflowHeight;
            float overflowFrame = currentFrame - startLayerFrames;
            // THIS BREAKS FOR NO REASON AT CERTAIN RESOLUTIONS FROM WHAT I CAN TELL
            // SPECIFICALLY SEEMINGLY AT EHS BACKGROUND WITH 2048x2048 MAX ATLAS
            // BUT THAT ALSO SEEMED TO FIX ISELF SO I DONT EVEN KNOW ANYMORE
            // "IF IT WORKS, IT WORKS"
            float frameInLayer = mod(overflowFrame, framesPerLayer);
            layer = startLayer + floor((overflowFrame - frameInLayer) / framesPerLayer) + 1.0;
            
            float x = mod(frameInLayer, overflowWidth);
            float y = floor(frameInLayer / overflowWidth);
            texturePos = vec2(x * frameSize.x, y * frameSize.y);
        }
    }


    v_textureUV = vec4(
        texturePos.x / atlasSize.x, 
        texturePos.y / atlasSize.y, 
        (texturePos.x + frameSize.x) / atlasSize.x, 
        (texturePos.y + frameSize.y) / atlasSize.y
    );
    v_texLayer = layer;
    gl_Position = vec4(worldPos, 0.0, 1.0);
}